
# /afs/csail.mit.edu/u/r/rasmus/projects/rasmus/python/rasmus/sexp/sexp_tab.py
# This file is automatically generated. Do not edit.
_tabversion = '3.2'

_lr_method = 'LALR'

_lr_signature = '\x00\xf2a\x8eX\xdf\xb1\xb6\xddx\xe0/\xf1~\x01\x99'
    
_lr_action_items = {'STRING':([2,4,5,6,7,8,9,10,],[4,-6,-5,-7,-4,4,-8,-1,]),')':([2,3,4,5,6,7,8,9,10,11,],[-3,10,-6,-5,-7,-4,-3,-8,-1,-2,]),'(':([0,2,4,5,6,7,8,9,10,],[2,2,-6,-5,-7,-4,2,-8,-1,]),'SYMBOL':([2,4,5,6,7,8,9,10,],[5,-6,-5,-7,-4,5,-8,-1,]),'NUMBER':([2,4,5,6,7,8,9,10,],[6,-6,-5,-7,-4,6,-8,-1,]),'BOOL':([2,4,5,6,7,8,9,10,],[9,-6,-5,-7,-4,9,-8,-1,]),'$end':([1,10,],[0,-1,]),}

_lr_action = { }
for _k, _v in _lr_action_items.items():
   for _x,_y in zip(_v[0],_v[1]):
      if not _x in _lr_action:  _lr_action[_x] = { }
      _lr_action[_x][_k] = _y
del _lr_action_items

_lr_goto_items = {'sexp':([0,2,8,],[1,7,7,]),'item_list':([2,8,],[3,11,]),'item':([2,8,],[8,8,]),}

_lr_goto = { }
for _k, _v in _lr_goto_items.items():
   for _x,_y in zip(_v[0],_v[1]):
       if not _x in _lr_goto: _lr_goto[_x] = { }
       _lr_goto[_x][_k] = _y
del _lr_goto_items
_lr_productions = [
  ("S' -> sexp","S'",1,None,None,None),
  ('sexp -> ( item_list )','sexp',3,'p_sexp','/afs/csail.mit.edu/u/r/rasmus/projects/rasmus/python/rasmus/sexp/parser.py',72),
  ('item_list -> item item_list','item_list',2,'p_item_list','/afs/csail.mit.edu/u/r/rasmus/projects/rasmus/python/rasmus/sexp/parser.py',78),
  ('item_list -> <empty>','item_list',0,'p_item_list','/afs/csail.mit.edu/u/r/rasmus/projects/rasmus/python/rasmus/sexp/parser.py',79),
  ('item -> sexp','item',1,'p_item','/afs/csail.mit.edu/u/r/rasmus/projects/rasmus/python/rasmus/sexp/parser.py',89),
  ('item -> SYMBOL','item',1,'p_item','/afs/csail.mit.edu/u/r/rasmus/projects/rasmus/python/rasmus/sexp/parser.py',90),
  ('item -> STRING','item',1,'p_item','/afs/csail.mit.edu/u/r/rasmus/projects/rasmus/python/rasmus/sexp/parser.py',91),
  ('item -> NUMBER','item',1,'p_item','/afs/csail.mit.edu/u/r/rasmus/projects/rasmus/python/rasmus/sexp/parser.py',92),
  ('item -> BOOL','item',1,'p_item','/afs/csail.mit.edu/u/r/rasmus/projects/rasmus/python/rasmus/sexp/parser.py',93),
]
