
# /afs/csail.mit.edu/u/r/rasmus/projects/rasmus/python/rasmus/treelib_tab.py
# This file is automatically generated. Do not edit.
_tabversion = '3.2'

_lr_method = 'LALR'

_lr_signature = '\x06\xf2\x8b\xed\x0f\xda@\xff[\x8f\x15\xad?6U\xb5'
    
_lr_action_items = {'NAME':([0,2,10,11,],[1,1,12,1,]),')':([1,4,6,7,8,10,12,13,],[-4,-8,10,-6,-7,-3,-2,-5,]),'(':([0,2,11,],[2,2,2,]),',':([1,4,7,8,10,12,],[-4,-8,11,-7,-3,-2,]),';':([1,4,5,8,10,12,],[-4,-8,9,-7,-3,-2,]),'DATA':([1,4,10,12,],[-4,8,-3,-2,]),'$end':([3,9,],[0,-1,]),}

_lr_action = { }
for _k, _v in _lr_action_items.items():
   for _x,_y in zip(_v[0],_v[1]):
      if not _x in _lr_action:  _lr_action[_x] = { }
      _lr_action[_x][_k] = _y
del _lr_action_items

_lr_goto_items = {'branch_set':([2,11,],[6,13,]),'tree':([0,],[3,]),'subtree':([0,2,11,],[4,4,4,]),'branch':([0,2,11,],[5,7,7,]),}

_lr_goto = { }
for _k, _v in _lr_goto_items.items():
   for _x,_y in zip(_v[0],_v[1]):
       if not _x in _lr_goto: _lr_goto[_x] = { }
       _lr_goto[_x][_k] = _y
del _lr_goto_items
_lr_productions = [
  ("S' -> tree","S'",1,None,None,None),
  ('tree -> branch ;','tree',2,'p_tree','/afs/csail.mit.edu/u/r/rasmus/projects/rasmus/python/rasmus/treelib_parser.py',44),
  ('subtree -> ( branch_set ) NAME','subtree',4,'p_subtree','/afs/csail.mit.edu/u/r/rasmus/projects/rasmus/python/rasmus/treelib_parser.py',50),
  ('subtree -> ( branch_set )','subtree',3,'p_subtree','/afs/csail.mit.edu/u/r/rasmus/projects/rasmus/python/rasmus/treelib_parser.py',51),
  ('subtree -> NAME','subtree',1,'p_subtree','/afs/csail.mit.edu/u/r/rasmus/projects/rasmus/python/rasmus/treelib_parser.py',52),
  ('branch_set -> branch , branch_set','branch_set',3,'p_branch_set','/afs/csail.mit.edu/u/r/rasmus/projects/rasmus/python/rasmus/treelib_parser.py',62),
  ('branch_set -> branch','branch_set',1,'p_branch_set','/afs/csail.mit.edu/u/r/rasmus/projects/rasmus/python/rasmus/treelib_parser.py',63),
  ('branch -> subtree DATA','branch',2,'p_branch','/afs/csail.mit.edu/u/r/rasmus/projects/rasmus/python/rasmus/treelib_parser.py',74),
  ('branch -> subtree','branch',1,'p_branch','/afs/csail.mit.edu/u/r/rasmus/projects/rasmus/python/rasmus/treelib_parser.py',75),
]
