#!/usr/bin/env python

import sys, optparse

from rasmus import util
from rasmus import treelib

from compbio import fasta
from compbio import phylo


o = optparse.OptionParser()
o.add_option("-S", "--smap", dest="smap", metavar="<gene2speces map>")
o.add_option("-s", "--stree", dest="stree", metavar="<species tree>")
o.add_option("-F", "--fastaext", dest="fastaext", metavar="<fasta extension>")
o.add_option("-T", "--treeext", dest="treeext", metavar="<tree extension>")

conf, args = o.parse_args()


#=============================================================================
gene2species = phylo.read_gene2species(conf.smap)
stree = treelib.read_tree(conf.stree)
    
util.tic("species tree -> gene tree")
    
i = 0
for f in args:
    i += 1
    util.logger("%d of %d (%s)" % (i, len(args), f))
        
    seqs = fasta.read_fasta(f)
    tree = phylo.stree2gtree(stree, seqs.keys(), gene2species)
    tree.write(util.replace_ext(f, conf.fastaext, conf.treeext))

util.toc()


