#!/usr/bin/env python
# Tue Nov 10 23:21:29 EST 2009
# convert between tree formats



import sys
import optparse

from rasmus import util
from rasmus import treelib


o = optparse.OptionParser()
o.add_option("-l", "--labels", dest="labels", metavar="FILENAME")

conf, args = o.parse_args()

informat, outformat = args


if informat == "ptree":
    tree = treelib.read_parent_tree(sys.stdin, conf.labels)

elif informat == "newick":
    tree = treelib.read_tree(sys.stdin)


if outformat == "ptree":
    labels = tree.leaf_names()
    tree.write_parent_tree(sys.stdout, tree, labels)
    util.write_list(conf.labels, tree, labels)
    
elif outformat == "newick":
    tree.write_newick(sys.stdout)

