#!/usr/bin/env python

import sys, optparse
from rasmus import util, treelib

from compbio import phylo

o = optparse.OptionParser()
o.add_option("-u", "--unroot", action="store_true",
             help="match unrooted topology")

conf, args = o.parse_args()

if len(args) != 2:
    print >>sys.stderr, "must give two trees"
    sys.exit(1)

tree1, tree2 = map(treelib.read_tree, args)

if conf.unroot:
    treelib.reroot(tree1, sorted(tree1.leaf_names())[0], newCopy=False)
    treelib.reroot(tree2, sorted(tree1.leaf_names())[0], newCopy=False)

hash1 = phylo.hash_tree(tree1)
hash2 = phylo.hash_tree(tree2)

print hash1 == hash2

if hash1 == hash2:
    sys.exit(0)
else:
    sys.exit(1)

