
# /mnt/big/archive/projects/examples/sexp/sexp/sexp_tab.py
# This file is automatically generated. Do not edit.
_tabversion = '3.2'

_lr_method = 'LALR'

_lr_signature = '\x0c\x83\x12\x90\x01 \x97\xb49\xd2\xe3:\xc3y%N'
    
_lr_action_items = {'STRING':([2,4,5,6,7,8,9,10,11,],[5,-5,-7,-6,-8,-4,5,-9,-1,]),')':([2,3,4,5,6,7,8,9,10,11,12,],[-3,11,-5,-7,-6,-8,-4,-3,-9,-1,-2,]),'(':([0,2,4,5,6,7,8,9,10,11,],[2,2,-5,-7,-6,-8,-4,2,-9,-1,]),'SYMBOL':([2,4,5,6,7,8,9,10,11,],[6,-5,-7,-6,-8,-4,6,-9,-1,]),'NUMBER':([2,4,5,6,7,8,9,10,11,],[7,-5,-7,-6,-8,-4,7,-9,-1,]),'BOOL':([2,4,5,6,7,8,9,10,11,],[10,-5,-7,-6,-8,-4,10,-9,-1,]),'$end':([1,11,],[0,-1,]),}

_lr_action = { }
for _k, _v in _lr_action_items.items():
   for _x,_y in zip(_v[0],_v[1]):
      if not _x in _lr_action:  _lr_action[_x] = { }
      _lr_action[_x][_k] = _y
del _lr_action_items

_lr_goto_items = {'sexp':([0,2,9,],[1,8,8,]),'item_list':([2,9,],[3,12,]),'word':([2,9,],[4,4,]),'item':([2,9,],[9,9,]),}

_lr_goto = { }
for _k, _v in _lr_goto_items.items():
   for _x,_y in zip(_v[0],_v[1]):
       if not _x in _lr_goto: _lr_goto[_x] = { }
       _lr_goto[_x][_k] = _y
del _lr_goto_items
_lr_productions = [
  ("S' -> sexp","S'",1,None,None,None),
  ('sexp -> ( item_list )','sexp',3,'p_sexp','/mnt/big/archive/projects/examples/sexp/sexp/parser.py',71),
  ('item_list -> item item_list','item_list',2,'p_item_list','/mnt/big/archive/projects/examples/sexp/sexp/parser.py',77),
  ('item_list -> <empty>','item_list',0,'p_item_list','/mnt/big/archive/projects/examples/sexp/sexp/parser.py',78),
  ('item -> sexp','item',1,'p_item','/mnt/big/archive/projects/examples/sexp/sexp/parser.py',87),
  ('item -> word','item',1,'p_item','/mnt/big/archive/projects/examples/sexp/sexp/parser.py',88),
  ('word -> SYMBOL','word',1,'p_word','/mnt/big/archive/projects/examples/sexp/sexp/parser.py',94),
  ('word -> STRING','word',1,'p_word','/mnt/big/archive/projects/examples/sexp/sexp/parser.py',95),
  ('word -> NUMBER','word',1,'p_word','/mnt/big/archive/projects/examples/sexp/sexp/parser.py',96),
  ('word -> BOOL','word',1,'p_word','/mnt/big/archive/projects/examples/sexp/sexp/parser.py',97),
]
